version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: newstrust-api-dev
    command: shotgun --host 0.0.0.0 --port 9292
    ports:
      - "9292:9292"
    depends_on:
      - redis
    environment:
      - DEBUG=true
      - RACK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    links:
      - redis
    volumes:
      - ${PWD}:/srv/app/news_trust
