version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: newstrust-api-test
    command: rake test
    depends_on:
      - redis
    environment:
      - DEBUG=true
      - RACK_ENV=test
      - REDIS_URL=redis://redis:6379/0
    links:
      - redis
    volumes:
      - ${PWD}:/srv/app/news_trust
